### ISSUE TITLE
Unable to enable basic authentication

### ISSUE THREAD

**Issue by Dearraj25** [zalando-incubator/es-operator#102]
Unable to enable basic authentication for elastic search with username and password.

Is there is any other way to enable authentication for elastic search with username and password?

I am trying to enable xpack.security I am facing errors.

 

I have just added xpack.security.enabled: true in es-config. 

 

```
apiVersion: v1

kind: ConfigMap

metadata:

  name: es-config

  namespace: es-operator-demo

data:

  elasticsearch.yml: |

    cluster.name: es-cluster

    network.host: "0.0.0.0"

    bootstrap.memory_lock: false

    discovery.seed_hosts: [es-master]

    cluster.initial_master_nodes: [es-master-0]

    xpack.security.enabled: true
```

 

I have tried different versions of elastic search dockers and also by changing the version of ES_JAVA_OPTS.

Used all the configuration given in https://github.com/zalando-incubator/es-operator/tree/master/docs.
