### ISSUE TITLE
Custom service

### ISSUE THREAD

**Issue by AyWa** [zalando-incubator/es-operator#113]
## Question

I have an overall question about `es-operator`. I am migrating from the official ES helm chart (for the data nodes the other node are still deploy with helm). However I am stuck to the last part: `configuring my ingress`

On the official helm chart, I can setup an ingress / services like:

```
ingress:
  enabled: True
  annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/target-type: instance
      alb.ingress.kubernetes.io/subnets: subnet-XX,subnet-YY
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 9200}]'
      alb.ingress.kubernetes.io/healthcheck-path: '/_cluster/health'
  hosts: [""]
  path: "/*"
  tls: []

service:
  type: LoadBalancer
``` 
Which will create 2 services (one load balancer and one headless)

However I can not (or find a way) to setup this load balancer correctly. From what I saw from the code, the operator need to own the service and will create a NodePort service. 

Does there is anyway to solve that ?

What I will do in the meantime is deploy some coordinate nodes with the load balancer, so I can access the Elasticsearch cluster (or do that on the master node for testing)
