### ISSUE TITLE
Irritating log message

### ISSUE THREAD

**Issue by otrosien** [zalando-incubator/es-operator#40]
## Expected Behavior

Only log that es-operator is scaling, if there is an actual change in replicas

## Actual Behavior

es-operator keeps logging "Updating desired scaling for EDS .... New desired replicas: 20. Decreasing node replicas to 20.", although the current replicas are already 20 (=minReplicas)

## Steps to Reproduce the Problem

One EDS that shows this behaviour

```
spec:
  replicas: 20
  scaling:
    diskUsagePercentScaledownWatermark: 0
    enabled: true
    maxIndexReplicas: 4
    maxReplicas: 40
    maxShardsPerNode: 30
    minIndexReplicas: 4
    minReplicas: 20
    minShardsPerNode: 12
    scaleDownCPUBoundary: 25
    scaleDownCooldownSeconds: 600
    scaleDownThresholdDurationSeconds: 600
    scaleUpCPUBoundary: 40
    scaleUpCooldownSeconds: 120
    scaleUpThresholdDurationSeconds: 60
```

## Specifications

Image `registry.opensource.zalan.do/poirot/es-operator:v0.1.0-17-gd237530`
