### ISSUE TITLE
Cooporation of Elasticsearch operators

### ISSUE THREAD

**Issue by mikkeloscar** [zalando-incubator/es-operator#65]
@pebrc @bleskes 

Based on our meeting at KubeCon we should see how the Zalando es-operator can work together with the elasticsearch operator: https://github.com/elastic/cloud-on-k8s

What should the interface be?

TBD.

**Comment by otrosien** [comment]
First thing to clarify is: in order not to confuse people make sure to state this operator is *not* the official one from Elastic. Also, do we violate any trademarks by naming our project "Elasticsearch operator" (I think we're slightly inconsistent as well, the tagline says for example "Kubernetes Operator for Elasticsearch" which would be my preferred naming)?

**Comment by pebrc** [comment]
I cannot answer  the trademark question. But I wanted to capture some of the discussion points from KubeCon. One idea for combining both operators we discussed was to run both operators next to each other. The basic idea being that they address orthogonal concerns at the moment. Elastic Cloud on Kubernetes manages clusters and does not implement any autoscaling while the Zalando operator does not manage the full cluster lifecycle but implements autoscaling.

The `Elasticsearch` resource exposes a `nodeCount` per node config section which is equivalent to the replica count in the stateful sets managed by the `ElasticsearchDataSet`s
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: elasticsearch-sample
spec:
  version: "7.1.0"
  nodes:
  - config:
      node.master: true
      node.data: true
     nodeCount: 1
```

So instead of managing stateful sets the Zalando es-operator could change the `nodeCount` property on the `Elasticsearch` CR. The ECK operator would then take care of adding new nodes in case of scale up or removing nodes after draining/vacating them in case of scale down. 

All other scaling operations would remain unchanged as they interact directly with the Elasticsearch API and would be handled by the Zalando operator.
